### ISSUE TITLE
Space in int unary param default causes error in game but is accepted by XS-CHECK

### ISSUE THREAD

**Issue by KSneijders** [Divy1211/xs-check#1]
Awesome tool as we discussed! ❤️ I found a minor issue:

The following XS Code is fine according to XS-Check:

# Script ([MRE](https://stackoverflow.com/help/minimal-reproducible-example))
```c
// ↓ Line "5" in default0.xs generated script ↓
void hi(int index = - 1) {
    // ...
}

void main() {
    hi(1);
}
```

# Result of XS-CHECK:
```
No errors found in file '<path>/default0.xs'! Your code is free of the pitfalls of XS' quirks =)
Finished analysing '<path>/default0.xs'.
```

# Result in game:
<img src="https://github.com/user-attachments/assets/c928f214-6e14-424e-a877-8a124a50ded5" width="400" />

# Notes:
Changing the function definition to the code below (removing the space) makes it work!
```
void hi(int index = -1) {
```

**Comment by Divy1211** [comment]
Fixed in v0.1.1
