### ISSUE TITLE
Empty file results in `TokenizationError`

### ISSUE THREAD

**Issue by KSneijders** [Divy1211/xs-check#3]
Referencing an empty file, or one with only whitespaces results in an error:

	Error: TokenizationError
	   ╭─[<path>:1:2]
	   │
	 1 │ 
	   │  │ 
	   │  ╰─ found end of input expected '/', '0', 't', 'f', '"', '+', '-', '*', '%', '<', '>', '=', '!', '&', '|', '(', ')', '{', '}', ';', ':', ',', or '.'
	───╯
	Finished analysing '<path>'.

**Comment by Divy1211** [comment]
Oo, this should be simple to fix, I will look into this soon, thanks for the report!

**Comment by Divy1211** [comment]
test

**Comment by Divy1211** [comment]
Fixed in v0.1.3
