### ISSUE TITLE
defining a too long int literal produces an error in xs but not in checker

### ISSUE THREAD

**Issue by mardaravicius** [Divy1211/xs-check#4]
```c
int num = 1000000000;
```
would produce an error in xs:
```
Token Error 0003: more than 9 digits in the integer constant.
```
note that xs `int` can hold full 32bit range of ints but not let us define large ones.
this affects both positive and negative ints (not counting the `-`)

for float did not see a similar limit

**Comment by Divy1211** [comment]
Huh, this is something xs-check should be catching, not sure why it doesn't - I'll look into this, thanks for the report

**Comment by Divy1211** [comment]
![image](https://github.com/user-attachments/assets/0a01bde6-e4de-437c-9f99-f4f031dca41a)
An error is produced for me, could you please check you're on the latest version of xs-check? 0.1.2

**Comment by mardaravicius** [comment]
you are right, can't reproduce anymore
